### ISSUE TITLE
minor English tweaks

### ISSUE THREAD

**Issue by pasdechance** [scoute-dich/QuitSmoking#41] opened 2020-07-11 12:19 UTC
I have no idea how to do this the right way, but there are some English tweaks to be made in the "Health" section

[see here](https://github.com/pasdechance/QuitSmoking/commit/54cc59cf6505628beffd74127f4e591b12b7c855)

**Comment by mesnevi** [comment] 2020-07-11 13:32
Yes, strings in English definitely need some polishing. I guess (after several days of trying to break huge AndroidX patch in smaller ones and get a sane build) I just revert it, then straighten things out with translations (because Dutch one was affected and Italian one was added afterward), then we'll see what to do with Android X support.

**Comment by mesnevi** [comment] 2020-07-17 07:19
Discussed in #35 
The problem is that these headers are the same indeed as header3, though they all refer to slightly different health conditions (at least header3 and header10): heart attack vs. cardiac arrest vs. stroke (which is mentioned in header11). After some thought, I guess header10 and header13 were meant as header3 improvements. All mentioned headers are related to cardiovascular diseases, so in the light that we have another header related (header9, "Coronary arteries"), it's obvious that this needs some refactoring, too.

I guess all the work and discussion will continue there, so closing this one. 'Health' section will be refactored and rewritten to avoid confusion and repetitive/obscure headers.

**Closed by mesnevi** 2020-07-17 07:19 UTC
Labels: enhancement
